version: '3.8'

services:
  auth-api:
    image: auth-api
    container_name: auth-api
    hostname: auth-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - PORT=${PORT}
    ports:
      - 3011:80
    platform: linux/amd64
    restart: always

networks:
  default:
    external: true
    name: local-network