version: '3.8'

services:
  auth-api:
    image: auth-api
    container_name: auth-api
    hostname: auth-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}
      - GOOGLE_AUTH_CERT_ENDPOINT=${GOOGLE_AUTH_CERT_ENDPOINT}
      - PORT=${PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - 3011:80
    platform: linux/amd64
    restart: always

networks:
  default:
    external: true
    name: local-network