apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auth-api
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/jayfaustdev/auth-api
        env:
        - name: PORT
          value: 80
