apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auth-api
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/jayfaustdev/auth-api
        env:
        - name: AUTH_ISSUER
          value: AUTH_ISSUER
        - name: AUTH_AUDIENCE
          value: AUTH_AUDIENCE
        - name: GOOGLE_AUTH_CERT_ENDPOINT
          value: https://www.googleapis.com/oauth2/v1/certs
        - name: PORT
          value: 80
